apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      replicas: 2
      containers:
      - name: backend-user
        image: olajhidey10/udagram-api-user
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
